/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 src/models/assets/minecraft_golden_pickaxe.glb -t -o src/models/Pickaxe.tsx 
Author: COVE989 (https://sketchfab.com/cove989)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/minecraft-golden-pickaxe-7e997fabc49142438abca96b224e82c1
Title: Minecraft Golden Pickaxe
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import pickaxe from './assets/minecraft_golden_pickaxe.glb?url'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
  }
  materials: {
    palette: THREE.MeshStandardMaterial
  }
}


export default function Axe(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(pickaxe) as GLTFResult
  return (
    <group dispose={null} {...props}>
      <group rotation={[0, Math.PI / 1.8, -0.3]} scale={0.3}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.palette} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload(pickaxe)
