/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 src/assets/butchers_yard.glb -t -o src/BuchersYard.tsx 
Author: TheAvatar (https://sketchfab.com/TheAvatar)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/butchers-yard-c02509c0782c4e08ad9aa0cbb92742a7
Title: Butcher's Yard
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import BuchersYardUrl from './assets/butchers_yard.glb?url'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_14: THREE.Mesh
    Object_15: THREE.Mesh
    Object_16: THREE.Mesh
    Object_17: THREE.Mesh
    Object_18: THREE.Mesh
    Object_19: THREE.Mesh
    Object_20: THREE.Mesh
    Object_21: THREE.Mesh
    Object_22: THREE.Mesh
    Object_23: THREE.Mesh
    Object_24: THREE.Mesh
    Object_25: THREE.Mesh
    Object_26: THREE.Mesh
    Object_27: THREE.Mesh
    Object_28: THREE.Mesh
    Object_29: THREE.Mesh
    Object_30: THREE.Mesh
    Object_31: THREE.Mesh
    Object_32: THREE.Mesh
    Object_33: THREE.Mesh
    Object_34: THREE.Mesh
    Object_35: THREE.Mesh
    Object_36: THREE.Mesh
    Object_37: THREE.Mesh
    Object_38: THREE.Mesh
    Object_39: THREE.Mesh
    Object_40: THREE.Mesh
    Object_41: THREE.Mesh
    Object_42: THREE.Mesh
    Object_43: THREE.Mesh
    Object_44: THREE.Mesh
    Object_45: THREE.Mesh
    Object_46: THREE.Mesh
    Object_47: THREE.Mesh
    Object_48: THREE.Mesh
    Object_49: THREE.Mesh
    Object_50: THREE.Mesh
    Object_51: THREE.Mesh
    Object_52: THREE.Mesh
    Object_53: THREE.Mesh
    Object_54: THREE.Mesh
    Object_55: THREE.Mesh
    Object_56: THREE.Mesh
    Object_57: THREE.Mesh
    Object_58: THREE.Mesh
    Object_59: THREE.Mesh
  }
  materials: {
    Acacia_Wood_Stairs: THREE.MeshStandardMaterial
    Anvil: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    Birch_Wood_Stairs: THREE.MeshStandardMaterial
    Bookshelf: THREE.MeshStandardMaterial
    Carpet: THREE.MeshStandardMaterial
    Cauldron: THREE.MeshStandardMaterial
    Chest: THREE.MeshStandardMaterial
    Coal_Ore: THREE.MeshStandardMaterial
    Cobblestone: THREE.MeshStandardMaterial
    Cobblestone_Stairs: THREE.MeshStandardMaterial
    Cobblestone_Wall: THREE.MeshStandardMaterial
    Cobweb: THREE.MeshStandardMaterial
    Crafting_Table: THREE.MeshStandardMaterial
    Dandelion: THREE.MeshStandardMaterial
    Dirt: THREE.MeshStandardMaterial
    Double_Stone_Slab: THREE.MeshStandardMaterial
    Double_Wooden_Slab: THREE.MeshStandardMaterial
    Fence: THREE.MeshStandardMaterial
    Fence_Gate: THREE.MeshStandardMaterial
    Furnace: THREE.MeshStandardMaterial
    Glass_Pane: THREE.MeshStandardMaterial
    Grass: THREE.MeshStandardMaterial
    Grass_Block: THREE.MeshStandardMaterial
    Gravel: THREE.MeshStandardMaterial
    Hay_Bale: THREE.MeshStandardMaterial
    Iron_Bars: THREE.MeshStandardMaterial
    Iron_Door: THREE.MeshStandardMaterial
    Iron_Ore: THREE.MeshStandardMaterial
    Jungle_Wood_Stairs: THREE.MeshStandardMaterial
    Ladder: THREE.MeshStandardMaterial
    Large_Flowers: THREE.MeshStandardMaterial
    Leaves: THREE.MeshStandardMaterial
    Monster_Egg: THREE.MeshStandardMaterial
    Moss_Stone: THREE.MeshStandardMaterial
    Nether_Brick_Fence: THREE.MeshStandardMaterial
    Netherrack: THREE.MeshStandardMaterial
    Oak_Door: THREE.MeshStandardMaterial
    Oak_Wood_Stairs: THREE.MeshStandardMaterial
    Packed_Ice: THREE.MeshStandardMaterial
    Poppy: THREE.MeshStandardMaterial
    Redstone_Wire: THREE.MeshStandardMaterial
    Sand: THREE.MeshStandardMaterial
    Sandstone: THREE.MeshStandardMaterial
    Snow_layer: THREE.MeshStandardMaterial
    Spruce_Wood_Stairs: THREE.MeshStandardMaterial
    Stationary_Water: THREE.MeshStandardMaterial
    Stone: THREE.MeshStandardMaterial
    Stone_Bricks: THREE.MeshStandardMaterial
    Stone_Pressure_Plate: THREE.MeshStandardMaterial
    Stone_Slab: THREE.MeshStandardMaterial
    Torch: THREE.MeshStandardMaterial
    Trapdoor: THREE.MeshStandardMaterial
    Wood: THREE.MeshStandardMaterial
    Wood_Planks: THREE.MeshStandardMaterial
    Wooden_Pressure_Plate: THREE.MeshStandardMaterial
    Wooden_Slab: THREE.MeshStandardMaterial
    Wool: THREE.MeshStandardMaterial
  }
}

export default function BuchersYard(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(BuchersYardUrl) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Acacia_Wood_Stairs} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Anvil} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Birch_Wood_Stairs} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Bookshelf} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Carpet} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Cauldron} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Chest} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Coal_Ore} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Cobblestone} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Cobblestone_Stairs} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Cobblestone_Wall} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Cobweb} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Crafting_Table} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Dandelion} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.Dirt} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.Double_Stone_Slab} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.Double_Wooden_Slab} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Fence} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.Fence_Gate} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.Furnace} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.Glass_Pane} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.Grass} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.Grass_Block} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.Gravel} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.Hay_Bale} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.Iron_Bars} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.Iron_Door} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.Iron_Ore} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.Jungle_Wood_Stairs} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.Ladder} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.Large_Flowers} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.Leaves} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.Monster_Egg} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.Moss_Stone} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.Nether_Brick_Fence} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.Netherrack} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.Oak_Door} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.Oak_Wood_Stairs} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.Packed_Ice} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.Poppy} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.Redstone_Wire} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.Sand} />
        <mesh geometry={nodes.Object_45.geometry} material={materials.Sandstone} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.Snow_layer} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.Spruce_Wood_Stairs} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.Stationary_Water} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.Stone} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.Stone_Bricks} />
        <mesh geometry={nodes.Object_51.geometry} material={materials.Stone_Pressure_Plate} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.Stone_Slab} />
        <mesh geometry={nodes.Object_53.geometry} material={materials.Torch} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.Trapdoor} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.Wood_Planks} />
        <mesh geometry={nodes.Object_57.geometry} material={materials.Wooden_Pressure_Plate} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.Wooden_Slab} />
        <mesh geometry={nodes.Object_59.geometry} material={materials.Wool} />
      </group>
    </group>
  )
}

useGLTF.preload(BuchersYardUrl)
