/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 src/assets/minecraft_-_chicken.glb -t -o src/Chicken.tsx 
Author: Vincent Yanez (https://sketchfab.com/vinceyanez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/minecraft-chicken-2968358f83af441db2b8e7c097f0173e
Title: Minecraft - Chicken
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import ChickenUrl from './assets/minecraft_-_chicken.glb?url'
import { useRef,useState } from "react";
import Mark from './Mark';

type GLTFResult = GLTF & {
  nodes: {
    ['Chicken_02_-_Default_0']: THREE.Mesh
  }
  materials: {
    ['02_-_Default']: THREE.MeshStandardMaterial
  }
}

export default function Chicken(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(ChickenUrl) as GLTFResult
  const mark = useRef<THREE.Group>(null)
  const [isVisible, setIsVisible] = useState(false);

  const pointOver = () => {
    setIsVisible(true)
  }
  const piontLeave = () => {
    setIsVisible(false)
  }
  return (
    <group {...props} dispose={null} onPointerOver={pointOver} onPointerLeave={piontLeave}>
      <mesh geometry={nodes['Chicken_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[0, 0.5, -6]} />
      <group ref={mark} visible={isVisible}>
        <Mark scale={0.01} position={[0, 10, 0]}/>
      </group>
    </group>
  )
}

useGLTF.preload(ChickenUrl)
