/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 src/assets/minecraft_-_creeper.glb -t -o src/Creeper.tsx 
Author: Vincent Yanez (https://sketchfab.com/vinceyanez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/minecraft-creeper-fd66182f07e5408eb04fa5a88ae16055
Title: Minecraft - Creeper
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import CreeperURL from './assets/minecraft_-_creeper.glb?url'
import { useRef,useState } from "react";
import Mark from './Mark';

type ActionName = 'actionNameOne' | 'actionNameTwo';

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    ['Creeper_02_-_Default_0']: THREE.Mesh
  }
  materials: {
    ['02_-_Default']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}


export default function Creeper(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(CreeperURL) as GLTFResult
  const mark = useRef<THREE.Group>(null)
  const [isVisible, setIsVisible] = useState(false);

  const pointOver = () => {
    setIsVisible(true)
  }
  const piontLeave = () => {
    setIsVisible(false)
  }
  return (
    <group {...props} dispose={null} onPointerOver={pointOver} onPointerLeave={piontLeave}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes['Creeper_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[0, 0, -7]} />
      </group>
      <group ref={mark} visible={isVisible}>
        <Mark scale={0.01} position={[0, 13, 0]}/>
      </group>
    </group>
  )
}

useGLTF.preload(CreeperURL)
