/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 src/assets/minecraft_-_enderman.glb -t -o src/Enderman.tsx 
Author: Vincent Yanez (https://sketchfab.com/vinceyanez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/minecraft-enderman-216552744553461d960dd0cdf3a0592a
Title: Minecraft - Enderman
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import EndermanURL from './assets/minecraft_-_enderman.glb?url'
import { useRef,useState } from "react";
import Mark from './Mark';

type GLTFResult = GLTF & {
  nodes: {
    ['Enderman_02_-_Default_0']: THREE.Mesh
  }
  materials: {
    ['02_-_Default']: THREE.MeshStandardMaterial
  }
}

export default function Enderman(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(EndermanURL) as GLTFResult
  const mark = useRef<THREE.Group>(null)
  const [isVisible, setIsVisible] = useState(false);

  const pointOver = () => {
    setIsVisible(true)
  }
  const piontLeave = () => {
    setIsVisible(false)
  }
  return (
    <group {...props} dispose={null} onPointerOver={pointOver} onPointerLeave={piontLeave}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes['Enderman_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[0, 0, 5]} />
      </group>
      <group ref={mark} visible={isVisible}>
        <Mark scale={0.01} position={[0, 27, 0]}/>
      </group>
    </group>
  )
}

useGLTF.preload(EndermanURL)
