/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 src/assets/mark.glb -t -o src/Mark.tsx 
Author: Anthony Yanez (https://sketchfab.com/paulyanez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/question-mark-block-super-mario-bros-be464a0b81384de79f49d38f5632c3f3
Title: Question Mark Block (Super Mario Bros)
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import MarkURL from './assets/mark.glb?url'
import { useRef } from "react";
import { useFrame } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    ['Box005_09_-_Default_0']: THREE.Mesh
    ['Box005_03_-_Default_0']: THREE.Mesh
    ['Box005_02_-_Default_0']: THREE.Mesh
  }
  materials: {
    ['09_-_Default']: THREE.MeshStandardMaterial
    ['03_-_Default']: THREE.MeshStandardMaterial
    ['02_-_Default']: THREE.MeshStandardMaterial
  }
 }

export default function Mark(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(MarkURL) as GLTFResult
  const mark = useRef<THREE.Group>(null)
  useFrame(() => {
    if (mark.current) {
      // mark.current.rotation.x += 0.01;
      mark.current.rotation.y += 0.01;
    }
  }) 
  return (
    <group {...props} dispose={null}>
      <group ref={mark} position={[-35.116, 760.384, -5.424]} scale={[-1, 1, 372.566]}>
        <group position={[219.915, 0, 0.481]}>
          <mesh geometry={nodes['Box005_09_-_Default_0'].geometry} material={materials['09_-_Default']} />
          <mesh geometry={nodes['Box005_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
          <mesh geometry={nodes['Box005_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(MarkURL)
