/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 src/assets/minecraft.glb -t -o src/MinCraft.tsx 
Author: Thales Sardinha (https://sketchfab.com/Thales_Sardinha)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/minecraft-d3e4dce89c434520b41b7a837a1414c1
Title: Minecraft
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import MinecraftUrl from './assets/minecraft.glb?url'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_9: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_14: THREE.Mesh
    Object_16: THREE.Mesh
  }
  materials: {
    Grass: THREE.MeshStandardMaterial
    SideGrass: THREE.MeshStandardMaterial
    Stone: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    TreeTrunkSide: THREE.MeshStandardMaterial
    TreeTrunkTop: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
  }
}

export default function MineCraft(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(MinecraftUrl) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.586, 0.16, 1.931]} scale={0.096}>
        <mesh geometry={nodes.Object_11.geometry} material={materials.TreeTrunkSide} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.TreeTrunkTop} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Stone} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Glass} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Grass} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.Grass} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.SideGrass} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.Stone} />
      <mesh geometry={nodes.Object_9.geometry} material={materials['Material.002']} position={[0.987, 0.188, 1.589]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials['Material.005']} position={[0.586, 0.16, 1.931]} scale={0.096} />
    </group>
  )
}

useGLTF.preload(MinecraftUrl)
